.TH CBUILD 1 "2026-04-03" "" ""
.SH NAME
cbuild \- Build tool for cbuild projects
.SH SYNOPSIS
.B cbuild
<\fIsubcommand\fR>
.SH DESCRIPTION
Build tool for cbuild projects
.SH GLOBAL OPTIONS
.TP
.B \-w <value>, \-\-workspace <value>
Path to the workspace directory.
.TP
.B \-d, \-\-dry-run
Show commands without executing them.
.TP
.B \-h, \-\-help
Show this help message.
.SH SUBCOMMANDS
.SS build
Build the project

.B Synopsis:
cbuild build [target]

.B Options for build:
.TP
.B \-c <value>, \-\-config <value>
Build configuration to use (e.g., Debug, Release), comma separated
.TP
.B \-T <value>, \-\-toolchain <value>
Select toolchain to use.
.TP
.B \-t <value>, \-\-target <value>
Specific target to build/modify.
.SS build-deps
Build dependencies for a target

.B Synopsis:
cbuild build-deps <target>

.B Options for build-deps:
.TP
.B \-c <value>, \-\-config <value>
Build configuration to use (e.g., Debug, Release), comma separated
.TP
.B \-T <value>, \-\-toolchain <value>
Select toolchain to use.
.TP
.B \-t <value>, \-\-target <value>
Specific target to build/modify.
.SS clean
Clean build artifacts

.B Synopsis:
cbuild clean [target]

.B Options for clean:
.TP
.B \-c <value>, \-\-config <value>
Build configuration to use (e.g., Debug, Release), comma separated
.TP
.B \-T <value>, \-\-toolchain <value>
Select toolchain to use.
.TP
.B \-t <value>, \-\-target <value>
Specific target to build/modify.
.SS help
Show help for cbuild or a specific subcommand

.B Synopsis:
cbuild help [subcommand]

.SS inspect-headers
Inspect compile_commands headers and report highest-impact project headers

.B Synopsis:
cbuild inspect-headers [target]

.B Options for inspect-headers:
.TP
.B \-c <value>, \-\-config <value>
Build configuration to use (e.g., Debug, Release), comma separated
.TP
.B \-T <value>, \-\-toolchain <value>
Select toolchain to use.
.TP
.B \-t <value>, \-\-target <value>
Specific target to build/modify.
.SS test
Build and run tests

.B Synopsis:
cbuild test [target]

.B Options for test:
.TP
.B \-c <value>, \-\-config <value>
Build configuration to use (e.g., Debug, Release), comma separated
.TP
.B \-T <value>, \-\-toolchain <value>
Select toolchain to use.
.TP
.B \-t <value>, \-\-target <value>
Specific target to build/modify.
